### ISSUE TITLE
Simulator shuts down in headless mode + Python API  after 30 seconds

### ISSUE THREAD

**Issue by left4taco** [lgsvl/simulator#1405]
This is similar but slightly different to https://github.com/lgsvl/simulator/issues/1396 so I'm opening a new issue. 

The `comfig.yml` I'm using is:
```yaml
headless: true
read_only: false
api_hostname: "*"
api_port: 8181
cloud_url: "https://wise.svlsimulator.com"
```

The simulation profile in the website is 52c9044a-090a-426e-a169-db7ab8f70b14(if you can read from the backend). Basically it's in headless mode, with Python API and Autoware.Auto (Apex.AI).

After I clicked `Run simulation`, the window did turn into a 3D map with a car, and I can control the car with keyboard. However, no matter what I do, it alway shuts down after 30 seconds and go back to the original window(dark blue background with  two rose-color buttons) and the status in the website goes back to `idle`. 

Is there a log that I can upload to help debug? Thanks
