### ISSUE TITLE
Camera point of view in sim doesn't match sensor config

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#1474]
Hello, 
I have made a new sensor configuration for the Lexus2016RXHybrid. And the camera look good in the web preview but the image I get from the simulator in ROS is clearly wrong. Here is my current config : 

![image](https://user-images.githubusercontent.com/22786578/120786195-a14cc180-c536-11eb-8acf-3a63c35224dd.png)

<details>
  <summary><b>Click here to see YAML</b></summary>
      
```yaml
[
  {
    "params": {
      "Topic": "/radar_fc"
    },
    "transform": {
      "x": 0,
      "y": 0.07,
      "z": 4,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    },
    "name": "Radar Sensor",
    "parent": "adjusted_base_link",
    "pluginId": "215b7d1e-7ad3-4fe6-b3d9-db0e229eb0a4",
    "plugin": {
      "assetGuid": "68ddcc86-1b72-447e-8b48-736917e07281",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "215b7d1e-7ad3-4fe6-b3d9-db0e229eb0a4",
      "name": "Radar Sensor",
      "type": "RadarSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This sensor outputs the objects detected by the radar. Detected objects are visualized with a box colored by their type:\n\t[\n\t\t\"Car\": \"Green\"\n\t\t\"Bicycle\": \"Cyan\"\n\t\t\"Agent\": \"Magenta\"\n\t]\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#radar for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "RadarSensor"
  },
  {
    "transform": {
      "x": 0,
      "y": 0,
      "z": -0.4,
      "pitch": 0,
      "roll": 0,
      "yaw": 0
    },
    "name": "adjusted_base_link",
    "parent": null,
    "pluginId": "71b0976e-cb87-4c11-ace2-14434aeec8a0",
    "plugin": {
      "assetGuid": "df34f7b7-a308-459e-b35b-fb1409a66baa",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "71b0976e-cb87-4c11-ace2-14434aeec8a0",
      "name": "Transform Sensor",
      "type": "TransformSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This sensor is specifically used to parent other sensors. For example, if there is a cluster of sensors, a Transform sensor can be added at the location of the cluster and then the individual sensors can have a transform that is relative to the location of the Transform sensor.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#transform-sensor for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "TransformSensor"
  },
  {
    "params": {
      "Topic": "/camera_fr/image/compressed"
    },
    "transform": {
      "x": 0.26893,
      "y": -0.65117,
      "z": 1.0776,
      "pitch": -9.21352384,
      "yaw": 26.221051,
      "roll": 5.3800737
    },
    "name": "camera_fr",
    "parent": "Center Lidar",
    "pluginId": "3d4f1e08-4c62-4e9f-b859-b26d4910b85e",
    "plugin": {
      "assetGuid": "e8bb3908-0059-4829-8cc3-4ba07dd915bf",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "3d4f1e08-4c62-4e9f-b859-b26d4910b85e",
      "name": "Color Camera Sensor",
      "type": "ColorCameraSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This is the type of sensor that would be used for the Main Camera in Apollo.\nColor Camera also has multiple post processing sensor effects that can be added to the Postprocessing field in params. Effects can be combined with an array of Postprocessing fields but order is hard coded.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "ColorCameraSensor"
  },
  {
    "params": {
      "Frequency": 12.5,
      "Topic": "/odom",
      "Frame": "gps",
      "IgnoreMapOrigin": true
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    },
    "name": "GPS Odometry",
    "parent": "adjusted_base_link",
    "pluginId": "483f7b90-2f76-42ee-82c1-22f02f25f924",
    "plugin": {
      "assetGuid": "f30ddcc6-7853-4282-8b0a-305d18827f03",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "483f7b90-2f76-42ee-82c1-22f02f25f924",
      "name": "GPS Odometry Sensor",
      "type": "GpsOdometrySensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This sensor outputs the GPS location of the vehicle in Longitude/Latitude and Northing/Easting coordintates and the vehicle velocity.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#gps-odometry for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "GpsOdometrySensor"
  },
  {
    "params": {
      "Topic": "/gps/imu",
      "Frame": "imu"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    },
    "name": "IMU",
    "parent": "adjusted_base_link",
    "pluginId": "9c34ec28-627d-4e73-9bb0-9c2aa7e978f5",
    "plugin": {
      "assetGuid": "d50ac8b1-0166-44a6-8499-5d8ecf7c8527",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "9c34ec28-627d-4e73-9bb0-9c2aa7e978f5",
      "name": "IMU Sensor",
      "type": "ImuSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This sensor output at a fixed rate of 100 Hz. IMU publishes data on topics where the 2nd topic has corrected IMU data.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#imu for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "ImuSensor"
  },
  {
    "params": {
      "LaserCount": 128,
      "RotationFrequency": 10,
      "MeasurementsPerRotation": 1024,
      "Topic": "/lidar_center/points_raw"
    },
    "transform": {
      "x": 0,
      "y": 1.78734,
      "z": 1.02,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    },
    "name": "Center Lidar",
    "parent": "adjusted_base_link",
    "pluginId": "b30d0478-8c7b-4687-bfc2-b3cdb3f5faff",
    "plugin": {
      "assetGuid": "aa5e3262-fde7-4445-b86e-0922ed5fedba",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "b30d0478-8c7b-4687-bfc2-b3cdb3f5faff",
      "name": "Lidar Sensor",
      "type": "LidarSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This sensor returns a point cloud after 1 revolution.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#lidar for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "LidarSensor"
  },
  {
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    },
    "name": "Keyboard Car Control",
    "parent": "adjusted_base_link",
    "pluginId": "a2ff904a-ff06-4f06-9e45-cb58217a7142",
    "plugin": {
      "assetGuid": "ec968dc8-2e34-4307-8d3a-9bbffdf9e6cc",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "a2ff904a-ff06-4f06-9e45-cb58217a7142",
      "name": "Keyboard Control Sensor",
      "type": "KeyboardControlSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This sensor is required for a vehicle to accept keyboard control commands. Parameters are not required.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#keyboard-control for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "KeyboardControlSensor"
  },
  {
    "params": {
      "Width": 1444,
      "Height": 1080,
      "Topic": "/camera_fl/image/compressed"
    },
    "transform": {
      "x": -0.17502,
      "y": -0.66163,
      "z": 1.11787,
      "pitch": -5.41366775,
      "roll": -0.3626822843,
      "yaw": 5.51836698
    },
    "name": "camera_fl",
    "parent": "Center Lidar",
    "pluginId": "3d4f1e08-4c62-4e9f-b859-b26d4910b85e",
    "plugin": {
      "assetGuid": "e8bb3908-0059-4829-8cc3-4ba07dd915bf",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "3d4f1e08-4c62-4e9f-b859-b26d4910b85e",
      "name": "Color Camera Sensor",
      "type": "ColorCameraSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This is the type of sensor that would be used for the Main Camera in Apollo.\nColor Camera also has multiple post processing sensor effects that can be added to the Postprocessing field in params. Effects can be combined with an array of Postprocessing fields but order is hard coded.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "ColorCameraSensor"
  },
  {
    "params": {
      "Frequency": 12.5,
      "Topic": "/nmea_sentence",
      "Frame": "gps",
      "IgnoreMapOrigin": false
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 90,
      "roll": 0
    },
    "name": "GPS",
    "parent": "adjusted_base_link",
    "pluginId": "75bbcbfa-fdca-4703-8e82-abf8078f7991",
    "plugin": {
      "assetGuid": "328b2afb-78c4-4c86-8a18-62015194a3fe",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "75bbcbfa-fdca-4703-8e82-abf8078f7991",
      "name": "GPS Device Sensor",
      "type": "GpsSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "This sensor outputs the GPS location of the vehicle in Longitude/Latitude and Northing/Easting coordintates.\nSee https://www.svlsimulator.com/docs/simulation-content/sensors-list/#gps-device for more details.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "GpsSensor"
  },
  {
    "params": {
      "Topic": "/vehicle_cmd"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    },
    "name": "Autoware Car Control",
    "parent": "adjusted_base_link",
    "pluginId": "76ff7bd1-81bf-4284-b9bf-e8173dc6053e",
    "plugin": {
      "assetGuid": "17b274f6-6d9c-4356-a7fc-23b078bfaaea",
      "isFavored": true,
      "isShared": false,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "id": "76ff7bd1-81bf-4284-b9bf-e8173dc6053e",
      "name": "AutowareAi Control Sensor",
      "type": "AutowareAiControlSensor",
      "category": "sensor",
      "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
      "accessType": "public",
      "description": "Sensor for subscribing to vehicle control topic from Autoware AI to drive the ego vehicle in the simulator.",
      "copyright": "LG Electronics Inc.",
      "licenseName": "LG Content",
      "status": "active",
      "owner": {
        "id": "0d888b00-fa53-47c1-882a-b68391268a11",
        "firstName": "SVL",
        "lastName": "Content"
      }
    },
    "type": "AutowareAiControlSensor"
  }
]
```
</details>

The problem is on the front right camera behind the windshield.

Here's the view from the front left camera (good) 
![image](https://user-images.githubusercontent.com/22786578/120786625-1e783680-c537-11eb-815f-161ee65b7468.png)

Here's the view from the front right camera (bad)
![image](https://user-images.githubusercontent.com/22786578/120786693-33ed6080-c537-11eb-8bb6-548dc670af17.png)

What could I do to solve this problem ? 
Thanks !

**[Edit] Solved after restarting the simulator twice.**
