### ISSUE TITLE
Add ring information to the cloud points

### ISSUE THREAD

**Issue by xmfcx** [lgsvl/simulator#1958]
Currently the [PointCloud2](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/PointCloud2.html) messages that are sent through the ROS2 are structured as following:

**Existing point structure:**

```yaml
fields: x, y, z, intensity, timestamp
types: FLOAT32, FLOAT32, FLOAT32, UINT8, FLOAT64
offsets: 0, 4, 8, 16, 24
point_step: 32
```

In Autoware.Auto we would like to perform filtering operations based on the rings (as in VLP16 would have 16 rings) these points belong to.

This is the package that would perform this filtering operation: https://github.com/tier4/AutowareArchitectureProposal.iv/blob/use-autoware-auto-msgs/sensing/preprocessor/pointcloud/pointcloud_preprocessor/docs/ring-outlier-filter.md

**Proposed point structure:**

```yaml
fields: x, y, z, intensity, **ring**, timestamp
types: FLOAT32, FLOAT32, FLOAT32, UINT8, **UINT16**, FLOAT64
offsets: 0, 4, 8, 16, **20**, 24
point_step: 32
```

It could be added to the existing points without changing the point size, right after the intensity.

The ring value would be an integer `[0 -> N]` where N is the `number of lasers - 1`, ordered top to bottom.

Would it be possible to add the ring information to the point clouds published by the SVL Simulator?

If we wanted to add this, which files would we need to change? Maybe we could initiate a PR for this too.
