### ISSUE TITLE
rosbridge testing

### ISSUE THREAD

**Issue by kk2491** [lgsvl/simulator#258]
Hi Guys,

Kindly help me in the below issue.

I am using the compiled version of LG simulator and trying to setup the ```rosbridge```. 
As given in the docs I run ```roslaunch rosbridge_server rosbridge_websocket.launch``` to start the ```rosbridge```. I could see that the simulator is now connected and able to launch the simulator successfully. 

![image](https://user-images.githubusercontent.com/38481564/62183147-9f33dd80-b376-11e9-8839-113ce956b629.png)

In my local system when I run ```rostopic list``` I get the following output.

```
kk@localsys:~$ rostopic list
/apollo/sensor/camera/traffic/image_long/compressed
/client_count
/connected_clients
/lanefollowing/steering_cmd
/rosout
/rosout_agg
/simulator/control/command
/simulator/reset
/simulator/sensor/camera/center/compressed
/simulator/sensor/camera/left/compressed
/simulator/sensor/camera/right/compressed
/simulator/sensor/segmentation_camera/compressed
/simulator/sensors/lidar
```

I want to send some test messages to the control topic and see how the car is behaving. 

It seems like the topic related to the control is ```/simulator/control/command```.  But car is not moving when I try to publish test messages to that topic.

```
kk@localsys:~$ rostopic pub -r 2 /simulator/control/command geometry_msgs/TwistStamped "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
twist:
  linear:
    x: 0.5
    y: 0.0
    z: 0.0
  angular:
    x: 0.0
    y: 0.0
    z: 0.0" 
````

Could you please let me know what I am doing wrong here?

Thank you,
KK
